/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asset/tank.glb --keepnames --keepgroups -o src/TankModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Super_Tank_1: THREE.Mesh
    Super_Tank_2: THREE.Mesh
    Super_Tank_3: THREE.Mesh
    Super_Tank_4: THREE.Mesh
    Super_Tank_5: THREE.Mesh
    Super_Tank_6: THREE.Mesh
    Super_Tank_7: THREE.Mesh
  }
  materials: {
    Black_SuperTank: THREE.MeshStandardMaterial
    Green_SuperTank: THREE.MeshStandardMaterial
    Yellow_SuperTank: THREE.MeshStandardMaterial
    DarkGreen_SuperTank: THREE.MeshStandardMaterial
    Gray_SuperTank: THREE.MeshStandardMaterial
    Orange_SuperTank: THREE.MeshStandardMaterial
    DarkBlue_SuperTank: THREE.MeshStandardMaterial
  }
}

export function TankModel(props: React.ComponentProps<'group'> & { color?: string }) {
  const { nodes, materials } = useGLTF('/tank.glb') as unknown as GLTFResult
  
  // Clone materials to apply custom colors if needed
  const customMaterial = React.useMemo(() => {
    if (!props.color) return materials.Green_SuperTank;
    const mat = materials.Green_SuperTank.clone();
    mat.color.set(props.color);
    return mat;
  }, [props.color, materials]);

  return (
    <group {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Super_Tank" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Super_Tank_1" geometry={nodes.Super_Tank_1.geometry} material={materials.Black_SuperTank} />
            <mesh name="Super_Tank_2" geometry={nodes.Super_Tank_2.geometry} material={customMaterial} />
            <mesh name="Super_Tank_3" geometry={nodes.Super_Tank_3.geometry} material={materials.Yellow_SuperTank} />
            <mesh name="Super_Tank_4" geometry={nodes.Super_Tank_4.geometry} material={materials.DarkGreen_SuperTank} />
            <mesh name="Super_Tank_5" geometry={nodes.Super_Tank_5.geometry} material={materials.Gray_SuperTank} />
            <mesh name="Super_Tank_6" geometry={nodes.Super_Tank_6.geometry} material={materials.Orange_SuperTank} />
            <mesh name="Super_Tank_7" geometry={nodes.Super_Tank_7.geometry} material={materials.DarkBlue_SuperTank} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tank.glb')
